version: "3"

services:
  mysqldb:
    image: mysql:8.2
    restart: unless-stopped
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - ${SQL_LOCAL_PORT}:${SQL_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
  app:
    depends_on:
      - mysqldb
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: password-manager-app
    expose:
      - ${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/usr/src/app
      - ./nodemon.json:/usr/src/app/nodemon.json
    command: npm run dev
  
volumes:
  db: