version: '3.4'

services:
  passwordmanager.web:
    image: ${DOCKER_REGISTRY-}passwordmanagerweb
    container_name: passwordmanager.web
    build:
      context: .
      dockerfile: PasswordManager.Web/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - passwordmanager.db
  
  passwordmanager.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: passwordmanager.db
    ports:
      - "5533:1433"
    environment:
      - SA_PASSWORD=MyP@ssword
      - ACCEPT_EULA=Y
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
  # passwordmanager.client:
  #   container_name: passwordmanager.client
  #   build:
  #       context: .
  #       dockerfile: PasswordManager.Client/Dockerfile
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #   depends_on:
  #       - passwordmanager.web
 
# Define volumes
volumes:
  mssql_data:
